### PR TITLE
Fix/rework scripts

### PR DESCRIPTION
**Pull request by MaGering**
With this PR the following changes are added to the validation scripts:

- Fix calculation of temperature hub of the heat pump
- Fix preprocessing of heat pump by adding a third filter of raw data
- Add missing scripts for Histogram, Residuals, RMSE and Temperature hub calculation / plots
- Add preprocessing of different data format for chiller
- Adjust path handling
- Update README
- Implement option for user to choose whether resampled or or original data is evaluated
- Implement plots of raw data for chiller
- Adjust format

### CODE REVIEW

**Comment by MaGering** [comment]
@c-moeller I've pushed my changes of the validation scripts with this PR.

**Comment by MaGering** [comment]
I'm working on creating dummy data and the correct structure of directories for using the scripts.

**Comment by SabineHaas** [comment]
Nice! Thanks a lot! 
Shall we merge first or do you want to work in the same branch?

**Comment by MaGering** [comment]
I think I'll work in the same branch because with the missing directories the handling of the scripts might not be clear. So I'll fix this first. :)

**Comment by MaGering** [comment]
I sampled dummy data for the chiller and heat pump. To make clear, we use dummy data, I left an entry in the README.

**Review by SabineHaas — APPROVED** [review]
Superb :) Thanks a lot!

Could you please add a requirements.txt file (run `pip freeze > requirements.txt` in your activated virtualenv)? Then it's ready to merge :)

**Pull request merged**
